apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: tomcat
          image: tomcat:jdk11-openjdk-slim
          ports:
            - containerPort: 80