apiVersion: v1
kind: Pod
metadata:
  name: ""
  labels:
    app: ""
spec:
  containers:
    - name: tomcat
      image: tomcat:jdk11-openjdk-slim
      ports:
        - name: web
          containerPort: 80
